services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SoftPassio\MediaBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    SoftPassio\MediaBundle\Doctrine\MediaManager:
        arguments:
            $className: '%media.entities.media_class%'

    SoftPassio\MediaBundle\Service\MediaProvider:
        arguments:
            $targetDirectory: '%media.media_web_path%'

    SoftPassio\MediaBundle\Service\MediaValidation:
        arguments: ['%media.max_file_size%', '%media.allowed_mime_types%', '%media.groups%']

    SoftPassio\MediaBundle\Service\MediaUploader:
        arguments:
            $targetDirectory: '%media.media_root_dir%'

    SoftPassio\MediaBundle\Doctrine\MediaManagerInterface: '@SoftPassio\MediaBundle\Doctrine\MediaManager'

    SoftPassio\MediaBundle\Form\DataTransformer\MediaTransformer:
        arguments:
            $className: '%media.entities.media_class%'
